"""add game start and update time

Revision ID: 061f0bf664d7
Revises: b6fc61cb4ddf
Create Date: 2020-05-01 14:19:11.245019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '061f0bf664d7'
down_revision = 'b6fc61cb4ddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('refreshed', sa.DateTime(), nullable=True))
    op.add_column('game', sa.Column('started', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'started')
    op.drop_column('game', 'refreshed')
    # ### end Alembic commands ###
