"""add Game Status PLAYFINAL and finalcount

Revision ID: 09cd18d4b64a
Revises: bd76f217d059
Create Date: 2021-01-30 21:19:46.747884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09cd18d4b64a'
down_revision = 'bd76f217d059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('finalcount', sa.Integer(), nullable=True))
    op.add_column('statistic', sa.Column('finalcount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statistic', 'finalcount')
    op.drop_column('game', 'finalcount')
    # ### end Alembic commands ###
