"""add firsthalf to user

Revision ID: 0c77e317da29
Revises: 2d43474e32da
Create Date: 2020-04-19 13:03:50.667096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c77e317da29'
down_revision = '2d43474e32da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('firsthalf', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'firsthalf')
    # ### end Alembic commands ###
