"""add number of thrown dice to statistic

Revision ID: 18f13a149bea
Revises: e01382d72e9f
Create Date: 2020-06-02 19:08:20.617446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18f13a149bea'
down_revision = 'e01382d72e9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('throw_dice_count', sa.Integer(), nullable=True))
    op.add_column('statistic', sa.Column('throw_dice_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statistic', 'throw_dice_count')
    op.drop_column('game', 'throw_dice_count')
    # ### end Alembic commands ###
