"""game add is_mail_send

Revision ID: 2045bf0cce72
Revises: e3ac3f6ecd4c
Create Date: 2020-11-12 19:23:41.665943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2045bf0cce72'
down_revision = 'e3ac3f6ecd4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('is_mail_send', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'is_mail_send')
    # ### end Alembic commands ###
