"""Change Status

Revision ID: 23871b1f26a4
Revises: 5f9ec0d8cad5
Create Date: 2020-03-27 21:42:53.921989

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '23871b1f26a4'
down_revision = '5f9ec0d8cad5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('status2', sa.Enum('WAITING', 'STARTED', 'FINISCH', name='status2'), nullable=True))
    op.drop_column('game', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('status', mysql.ENUM('DEFERREDTRACKS', 'BILL', 'NOTBILL'), nullable=True))
    op.drop_column('game', 'status2')
    # ### end Alembic commands ###
