"""add User finalcount

Revision ID: 2c71994ad95b
Revises: 09cd18d4b64a
Create Date: 2021-01-31 09:19:47.084563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c71994ad95b'
down_revision = '09cd18d4b64a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('finalcount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'finalcount')
    # ### end Alembic commands ###
