"""add status

Revision ID: 2d43474e32da
Revises: 23871b1f26a4
Create Date: 2020-04-18 16:33:54.616207

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2d43474e32da'
down_revision = '23871b1f26a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('status', sa.Enum('WAITING', 'STARTED', 'ROUNDFINISCH', 'GAMEFINISCH', name='status'), nullable=True))
    op.drop_column('game', 'status2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('status2', mysql.ENUM('WAITING', 'STARTED', 'FINISCH'), nullable=True))
    op.drop_column('game', 'status')
    # ### end Alembic commands ###
