"""add dices to user

Revision ID: 607cb4c5dee9
Revises: c9352fba30ff
Create Date: 2020-03-22 20:45:14.687899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '607cb4c5dee9'
down_revision = 'c9352fba30ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('dice1', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('dice2', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('dice3', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'dice3')
    op.drop_column('user', 'dice2')
    op.drop_column('user', 'dice1')
    # ### end Alembic commands ###
