"""add Game Stack Max

Revision ID: 60bc09aa36e6
Revises: 2045bf0cce72
Create Date: 2021-01-24 10:24:09.839882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60bc09aa36e6'
down_revision = '2045bf0cce72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('stack_max', sa.Integer(), nullable=True))
    op.add_column('statistic', sa.Column('stack_max', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statistic', 'stack_max')
    op.drop_column('game', 'stack_max')
    # ### end Alembic commands ###
