"""add visible for each dice

Revision ID: 9937159f8e8c
Revises: 0c77e317da29
Create Date: 2020-04-19 19:20:14.486687

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9937159f8e8c'
down_revision = '0c77e317da29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('dice1_visible', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('dice2_visible', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('dice3_visible', sa.Boolean(), nullable=True))
    op.drop_column('user', 'visible')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('visible', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('user', 'dice3_visible')
    op.drop_column('user', 'dice2_visible')
    op.drop_column('user', 'dice1_visible')
    # ### end Alembic commands ###
