"""add schockoutcount and halfcount and Parent Class Statistic

Revision ID: b3e319ef9563
Revises: 980580d8d3f1
Create Date: 2020-05-17 15:12:35.413820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3e319ef9563'
down_revision = '980580d8d3f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('schockoutcount', sa.Integer(), nullable=True))
    op.add_column('game', sa.Column('usercount', sa.Integer(), nullable=True))
    op.add_column('statistic', sa.Column('schockoutcount', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('halfcount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'halfcount')
    op.drop_column('statistic', 'schockoutcount')
    op.drop_column('game', 'usercount')
    op.drop_column('game', 'schockoutcount')
    # ### end Alembic commands ###
