"""add Game play_final

Revision ID: bd76f217d059
Revises: 60bc09aa36e6
Create Date: 2021-01-30 20:02:58.571283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd76f217d059'
down_revision = '60bc09aa36e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('play_final', sa.Boolean(), nullable=True))
    op.add_column('statistic', sa.Column('play_final', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statistic', 'play_final')
    op.drop_column('game', 'play_final')
    # ### end Alembic commands ###
