"""first tabels

Revision ID: c9352fba30ff
Revises: 
Create Date: 2020-03-22 19:06:57.333889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9352fba30ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('UUID', sa.String(length=200), nullable=True),
    sa.Column('firsthalf', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('DEFERREDTRACKS', 'BILL', 'NOTBILL', name='status'), nullable=True),
    sa.Column('stack', sa.Integer(), nullable=True),
    sa.Column('changs_of_fallling_dice', sa.Float(), nullable=True),
    sa.Column('move_user_id', sa.Integer(), nullable=True),
    sa.Column('first_user_id', sa.Integer(), nullable=True),
    sa.Column('admin_user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_UUID'), 'game', ['UUID'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('chips', sa.Integer(), nullable=True),
    sa.Column('passive', sa.Boolean(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_game_UUID'), table_name='game')
    op.drop_table('game')
    # ### end Alembic commands ###
